/*
	Use this template to test all the parameters that are available in HDK.

	IMPORTANT! ------------------------------------------
	DO NOT MODIFY THIS FILE.
	Doing so may break every extension that uses it as a base or utility.
	Modify it ONLY when you know what you are doing. That means NEVER!
	-----------------------------------------------------

	TODO! -----------------------------------------------
	- add tooltips
	-----------------------------------------------------

	Author: 	Nodeway (2016)

	Email:		nodeway@hotmail.com
	Vimeo:		https://vimeo.com/nodeway
	Twitter:	https://twitter.com/nodeway
	Github:		https://github.com/nodeway
*/

#pragma once

/* -----------------------------------------------------------------
INCLUDES                                                           |
----------------------------------------------------------------- */

#include "Base/NW_SOP_Operator.h"

/* -----------------------------------------------------------------
OPERATOR SPECIFIC DEFINES                                          |
----------------------------------------------------------------- */

// -------------------------- Defaults //

#define SOP_PARAMETERSTEMPLATE_NAME											ParametersTemplate
#define SOP_PARAMETERSTEMPLATE_DATE											"2016"
// internal/external/icon name
#define SOP_PARAMETERSTEMPLATE_OP_SMALLNAME									"nodeway::parameterstemplate::1.0"
#define SOP_PARAMETERSTEMPLATE_OP_BIGNAME									"Parameters Template (HDK)"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_ICONNAME							"SOP_ParametersTemplate.svg"
// title
#define SOP_PARAMETERSTEMPLATE_OPERATOR_TITLE								"SOP PARAMETERS TEMPLATE v1.0"
// submenu
#define SOP_PARAMETERSTEMPLATE_SUBMENUPATH									"NODEWAY/HDK"
// inputs
#define SOP_PARAMETERSTEMPLATE_OPERATOR_INPUTNAME0							"Geometry"

// -------------------------- Parameters //

// switcher
#define SOP_PARAMETERSTEMPLATE_OPERATOR_SWITCHER_SMALLNAME					"switcher"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_SWITCHER_BIGNAME					"Switcher"
// parameter count
#define SOP_PARAMETERSTEMPLATE_OPERATOR_PARMCOUNTTAB0						9
#define SOP_PARAMETERSTEMPLATE_OPERATOR_PARMCOUNTTAB1						2
#define SOP_PARAMETERSTEMPLATE_OPERATOR_PARMCOUNTTAB2						4
// tabs
#define SOP_PARAMETERSTEMPLATE_OPERATOR_TABNAME0							"Standard"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_TABNAME1							"Ramps"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_TABNAME2							"Menus"

// collapsible
#define SOP_PARAMETERSTEMPLATE_OPERATOR_COLLAPSIBLESWITCHER_SMALLNAME		"collapsible_switcher"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_COLLAPSIBLESWITCHER_BIGNAME			"Collapsible Switcher"

// labels
#define SOP_PARAMETERSTEMPLATE_OPERATOR_LABEL_SMALLNAME						"label"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_LABEL_BIGNAME						"Label"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_LABEL_COLUMNNAME0					"Column 0"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_LABEL_COLUMNNAME1					"Column 1"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_LABELCENTERED_SMALLNAME				"label_centered"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_LABELCENTERED_BIGNAME				""
#define SOP_PARAMETERSTEMPLATE_OPERATOR_LABELCENTERED_COLUMNNAME0			"Centered"
// separator
#define SOP_PARAMETERSTEMPLATE_OPERATOR_SEPARATOR_SMALLNAME					"separator"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_SEPARATOR_BIGNAME					"Separator"
// toggle
#define SOP_PARAMETERSTEMPLATE_OPERATOR_TOGGLE_SMALLNAME					"toggle"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_TOGGLE_BIGNAME						"Toggle"
// int/float
#define SOP_PARAMETERSTEMPLATE_OPERATOR_INT_SMALLNAME						"int"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_INT_BIGNAME							"Int"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_INT_DEFAULT							10
#define SOP_PARAMETERSTEMPLATE_OPERATOR_INT_RANGEMIN						0
#define SOP_PARAMETERSTEMPLATE_OPERATOR_INT_RANGEMAX						23
#define SOP_PARAMETERSTEMPLATE_OPERATOR_FLOAT_SMALLNAME						"float"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_FLOAT_BIGNAME						"Float"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_FLOAT_DEFAULT						10.0f
#define SOP_PARAMETERSTEMPLATE_OPERATOR_FLOAT_RANGEMIN						0
#define SOP_PARAMETERSTEMPLATE_OPERATOR_FLOAT_RANGEMAX						23.0f
// textfield
#define SOP_PARAMETERSTEMPLATE_OPERATOR_TEXTFIELD_SMALLNAME					"text_field"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_TEXTFIELD_BIGNAME					"Text Field"
// vectors
#define SOP_PARAMETERSTEMPLATE_OPERATOR_VECTOR2_SMALLNAME					"vector2"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_VECTOR2_BIGNAME						"Vector2"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_VECTOR2_DEFAULTX					0
#define SOP_PARAMETERSTEMPLATE_OPERATOR_VECTOR2_DEFAULTY					1
#define SOP_PARAMETERSTEMPLATE_OPERATOR_VECTOR3_SMALLNAME					"vector3"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_VECTOR3_BIGNAME						"Vector3"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_VECTOR3_DEFAULTX					0
#define SOP_PARAMETERSTEMPLATE_OPERATOR_VECTOR3_DEFAULTY					-9.8f
#define SOP_PARAMETERSTEMPLATE_OPERATOR_VECTOR3_DEFAULTZ					0
// ramps
#define SOP_PARAMETERSTEMPLATE_OPERATOR_COLORRAMP_SMALLNAME					"color_ramp"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_COLORRAMP_BIGNAME					"Color Ramp"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_COLORRAMP_DEFAULT0					2
#define SOP_PARAMETERSTEMPLATE_OPERATOR_COLORRAMP_DEFAULT1					2
#define SOP_PARAMETERSTEMPLATE_OPERATOR_FLOATRAMP_SMALLNAME					"float_ramp"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_FLOATRAMP_BIGNAME					"Float Ramp"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_FLOATRAMP_DEFAULT0					2
#define SOP_PARAMETERSTEMPLATE_OPERATOR_FLOATRAMP_DEFAULT1					2
// menus
#define SOP_PARAMETERSTEMPLATE_OPERATOR_ORDINALMENU_SMALLNAME				"ordinal_menu"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_ORDINALMENU_BIGNAME					"Ordinal Menu"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_ORDINALMENU_CHOICE_SMALLNAME0		"choice0"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_ORDINALMENU_CHOICE_BIGNAME0			"Choice 0"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_ORDINALMENU_CHOICE_SMALLNAME1		"choice1"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_ORDINALMENU_CHOICE_BIGNAME1			"Choice 1"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_ORDINALMENU_CHOICE_SMALLNAME2		"choice2"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_ORDINALMENU_CHOICE_BIGNAME2			"Choice 2"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_STRINGMENU_SMALLNAME				"string_menu"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_STRINGMENU_BIGNAME					"String Menu"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_STRINGMENU_CHOICE_SMALLNAME0		"choice0"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_STRINGMENU_CHOICE_BIGNAME0			"Choice 0"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_STRINGMENU_CHOICE_SMALLNAME1		"choice1"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_STRINGMENU_CHOICE_BIGNAME1			"Choice 1"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_GROUPMENU_SMALLNAME					"group_menu"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_GROUPMENU_BIGNAME					"Group Menu"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_OBJECTPATHMENU_SMALLNAME			"object_path_menu"
#define SOP_PARAMETERSTEMPLATE_OPERATOR_OBJECTPATHMENU_BIGNAME				"Object Path Menu"

// -------------------------- Tooltip Help //